# Game Systems and their associated factions
# This file is used by the seed:game_systems rake task

game_systems:
  - name: "Epic Armaggeddon - FERC"
    description: 
      en: "6mm strategy – French community-maintained lists"
      fr: "Stratégie en 6mm – listes maintenues par la communauté française"
    factions:
      - "Adeptus Astartes"
      - "White Scars"
      - "Raven Guard"
      - "Space Wolves"
      - "Black Templars"
      - "Imperial Fists"
      - "Blood Angels"
      - fr: "Légion d'Acier"
        en: "Steel Legion"
      - fr: "Death Korp of Krieg"
        en: "Death Korp de Krieg"
      - "Paras Elysiens"
      - "Premiers-Nés Vostroyens"
      - "Légions Titaniques"
      - "Adeptus Mechanicus"
      - "Chevaliers Impériaux"
      - "Adepta Sororitas"
      - "Adeptus Arbites"
      - "Black Legion"
      - "Iron Warriors"
      - "Egarés et Damnés"
      - "World Eaters"
      - "Thousand Sons"
      - "Death Guard"
      - "Emperor's Children"
      - "Eldars de Biel-Tan"
      - "Eldars de Ulthwé"
      - "Eldars Noirs"
      - "Tyranides"
      - "Squats"
      - "Empire T'au"
      - "Orks"
      - "Nécrons"

  - name: "Warhammer 40k"
    description: "The best known Games Workshop game"
    factions:
      - "Chaos Knights"
      - "Agents de l'Imperium"
      - "Empire T'au"
      - "Space Wolves"
      - "Orks"
      - "Thousand Sons"
      - "Dark Angels"
      - "World Eaters"
      - "Tyranids"
      - "Aeldari"
      - "Space Marines du Chaos"
      - "Astra Militarum"
      - "Nécrons"
      - "Emperor's Children"
      - "Death Guard"
      - "Adeptus Custodes"
      - "Adepta Sororitas"
      - "Space Marines"
      - "Cultes Genestealers"
      - "Adeptus Mechanicus"
      - "Blood Angels"
      - "Deathwatch"
      - "Imperial Knights"
      - "Chevaliers Gris"
      - "Démons du Chaos"
      - "Drukhari"
      - "Leagues of Votann"
      - "Black Templars"
